### ISSUE TITLE
Generating peptide smiles with non-natural amino acids

### ISSUE THREAD

**Issue by amin-sagar** [rochoa85/PepFun2#1]
Hello.
Thanks for making this excellent library available.
From the description, I understand that it is possible to generate 3D structures with non-natural amino acids given the pdb of the non-natural amino acid.
However, it's not clear to me if I can just generate SMILES or an RDkit object from sequence without any 3D structure. My aim is to calculate properties using RDkit or pepfun2 based functions.
i.e. is it possible to do something like this (I know this exact line doesn't work )
seq = Sequence("K-Aib-Iva-P-L-C-D")

Best,
Amin.

**Comment by rochoa85** [comment]
Dear Amin

Thanks for your interest in PepFun. With this package, we can generate SMILES of natural peptides or calculate properties of single monomers (natural or non-natural) using the SMILES stored in the monomers.csv file. For PepFun is out of the scope to connect a peptide composed of natural and non-natural amino acids to generate an RDKit object. However, given the chemical complexity behind that task, this will be possible in a different package to be published in some weeks. If you are interested, I can let you know when it is released.

Rodrigo

**Comment by amin-sagar** [comment]
Thanks Rodrigo.
I look forward to your upcoming package. It would be great to know when it's released.
Best,
Amin.

**Comment by rochoa85** [comment]
Perfect, I will let you know

Rodrigo
